version: '3.8'
services:
  php54:
    container_name: php54
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php54/Dockerfile
    volumes:
      - ./php54/htdocs:/var/www/html
      - ./php54/logs:/var/log/apache2
      - ./php54/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${PHP54_HTTP_PORT-8054}:80
    links:
      - mysql80
      - mariadb55

  php56:
    container_name: php56
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php56/Dockerfile
    volumes:
      - ./php56/htdocs:/var/www/html
      - ./php56/logs:/var/log/apache2
      - ./php56/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${PHP56_HTTP_PORT-8056}:80
    links:
      - mysql80
      - mariadb55

  php83:
    container_name: php83
    restart: always
    build:
      context: .
      dockerfile: ./php83/Dockerfile
    volumes:
      - ./php83/htdocs:/var/www/html
      - ./php83/logs:/var/log/apache2
      - ./php83/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - ${PHP83_HTTP_PORT-8083}:80
    links:
      - mysql80
      - mariadb55

  mysql80:
    container_name: mysql80
    restart: always
    image: mysql:8.0
    volumes:
      - mysql80-data:/var/lib/mysql
      - ./mysql80/initdb:/docker-entrypoint-initdb.d
      - ./mysql80/logs:/var/log/mysql
      - ./mysql80/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MYSQL80_PORT-13306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test

  mariadb55:
    container_name: mariadb55
    restart: always
    image: mariadb:5.5
    volumes:
      - mariadb55-data:/var/lib/mysql
      - ./mariadb55/initdb:/docker-entrypoint-initdb.d
      - ./mariadb55/logs:/var/log/mysql
      - ./mariadb55/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${MARIADB55_PORT-13307}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test

  phpMyAdmin:
    container_name: phpMyAdmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: mysql80,mariadb55
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - ${PHPMYADMIN_HTTP_PORT-1080}:80
    depends_on:
      - mysql80
      - mariadb55

volumes:
  mysql80-data:
    name: mysql80-data
    driver: local
  mariadb55-data:
    name: mariadb55-data
    driver: local
