version: '3.8'
services:
  php54:
    container_name: php54
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php54/Dockerfile
    volumes:
      - ./php54/htdocs:/var/www/html
      - ./php54/logs:/var/log/apache2
    ports:
      - ${PHP54_HTTP_PORT-8054}:80
    depends_on:
      - mysql80

  php83:
    container_name: php83
    restart: always
    build:
      context: .
      dockerfile: ./php83/Dockerfile
    volumes:
      - ./php83/htdocs:/var/www/html
      - ./php83/logs:/var/log/apache2
    ports:
      - ${PHP83_HTTP_PORT-8083}:80
    depends_on:
      - mysql80

  mysql80:
    container_name: mysql80
    restart: always
    image: mysql/mysql-server:8.0
    volumes:
      - mysql80-data:/var/lib/mysql
      - ./mysql80/initdb:/docker-entrypoint-initdb.d
      - ./mysql80/logs:/var/log/mysql
    ports:
      - ${MYSQL_LATEST_PORT-13306}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test

  phpMyAdmin:
    container_name: phpMyAdmin
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql80
      PMA_USER: admin
      PMA_PASSWORD: password
    ports:
      - ${PHPMYADMIN_HTTP_PORT-1080}:80
    depends_on:
      - mysql80

volumes:
  mysql80-data:
    name: mysql80-data
    driver: local
